#!/bin/bash -e
export red="\033[31m"
done="\033[0m"

echo -e "${red}ARE YOU SURE THAT YOU WANT TO REMOVE THE POCO?${done}"
echo -ne "${red}TYPE [DELETE] TO REMOVE: ${done}"
read cmd
if [ "$cmd" == "DELETE" ]; then
  rm -f "$PREFIX/bin/poco"
  rm -rf "$PREFIX/etc/poco"
  rm -rf "$PREFIX/bin/poco-rescue"
  rm -rf "$PREFIX/bin/poco-remove"
  echo -e "${red}DONE${done}"
else 
  echo -e "${red}ERROR:INVALID OPERATION,RETURN STATUS [2]${done}"
  exit 2
fi
